import sqlite3

def init_db():
    conn = sqlite3.connect('database.db')
    c = conn.cursor()

    # Create tables first
    c.execute('''CREATE TABLE IF NOT EXISTS quotes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        text TEXT NOT NULL,
        author TEXT NOT NULL
    )''')
    
    c.execute('''CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL
    )''')

    # Now safe to delete duplicates
    c.execute("""
DELETE FROM quotes
WHERE id NOT IN (
    SELECT MIN(id)
    FROM quotes
    GROUP BY text, author
)
""")

    # Insert sample quotes only if table is empty
    c.execute("SELECT COUNT(*) FROM quotes")
    if c.fetchone()[0] == 0:
        c.executemany("INSERT INTO quotes (text, author) VALUES (?, ?)", [
            ("Believe you can and you're halfway there.", "Theodore Roosevelt"),
            ("The best way to get started is to quit talking and begin doing.", "Walt Disney"),
            ("Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"),
            ("To be, or not to be, that is the question.", "William Shakespeare"),
            ("Be kind, for everyone you meet is fighting a hard battle.","Plato"),
            ("One cannot think well, love well, sleep well, if one has not dined well.","Virginia Woolf"),
            ("The only way to do great work is to love what you do.", "Steve Jobs"),
            ("Life is what happens when you're busy making other plans.", "John Lennon"),
            ("Get busy living or get busy dying.", "Stephen King"),
            ("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"),
            ("Act as if what you do makes a difference. It does.", "William James"),
            ("Success is not final, failure is not fatal: It is the courage to continue that counts.", "Winston Churchill"),
            ("The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
            ("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"),
            ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
            ("Everything you've ever wanted is on the other side of fear.", "George Addair"),
            ("Opportunities don't happen, you create them.", "Chris Grosser"),
            ("Be yourself; everyone else is already taken.", "Oscar Wilde"),
            ("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
            ("The best way to predict the future is to create it.", "Peter Drucker"),
            ("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
            ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"),
            ("Act as if what you do makes a difference. It does.", "William James"),
            ("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
            ("You must be the change you wish to see in the world.", "Mahatma Gandhi"),
            ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
            ("It always seems impossible until it's done.", "Nelson Mandela"),
            ("Dream big and dare to fail.", "Norman Vaughan"),
            ("An unexamined life is not worth living.", "Socrates"),
            ("Turn your wounds into wisdom.", "Oprah Winfrey"),
            ("Everything you can imagine is real.", "Pablo Picasso"),
            ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
            ("Imagination is more important than knowledge.", "Albert Einstein"),
            ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
            ("Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis"),
            ("Success is how high you bounce when you hit bottom.", "George S. Patton"),
            ("The purpose of our lives is to be happy.", "Dalai Lama"),
            ("The harder you work for something, the greater you’ll feel when you achieve it.", "Unknown"),
            ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
            ("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
            ("Quality is not an act, it is a habit.", "Aristotle"),
            ("The secret of getting ahead is getting started.", "Mark Twain"),
            ("The way to get started is to quit talking and begin doing.", "Walt Disney"),
            ("Be yourself; everyone else is already taken.", "Oscar Wilde"),
            ("In the middle of every difficulty lies opportunity.", "Albert Einstein"),
            ("The best way to predict the future is to create it.", "Peter Drucker"),
            ("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"),
            ("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
            ("You must be the change you wish to see in the world.", "Mahatma Gandhi"),
            ("Dream big and dare to fail.", "Norman Vaughan"),
            ("An unexamined life is not worth living.", "Socrates"),
            ("Turn your wounds into wisdom.", "Oprah Winfrey"),
            ("Everything you can imagine is real.", "Pablo Picasso"),
            ("I have not failed. I've just found 10,000 ways that won't work.", "Thomas Edison"),
            ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
            ("Hardships often prepare ordinary people for an extraordinary destiny.", "C.S. Lewis"),
            ("Success is how high you bounce when you hit bottom.", "George S. Patton"),
            ("The purpose of our lives is to be happy.", "Dalai Lama"),
            ("Success is not how high you have climbed, but how you make a positive difference to the world.", "Roy T. Bennett"),
            ("Don't count the days, make the days count.", "Muhammad Ali"),
            ("Your life does not get better by chance, it gets better by change.", "Jim Rohn"),
            ("Don’t wait. The time will never be just right.", "Napoleon Hill"),
            ("The mind is everything. What you think you become.", "Buddha"),
            ("What you get by achieving your goals is not as important as what you become by achieving your goals.", "Zig Ziglar"),
            ("If you want to lift yourself up, lift up someone else.", "Booker T. Washington"),
            ("Everything has beauty, but not everyone sees it.", "Confucius"),
            ("Limit your 'always' and your 'nevers'.", "Amy Poehler"),
            ("Try to be a rainbow in someone else's cloud.", "Maya Angelou"),
            ("You do not find the happy life. You make it.", "Camilla Eyring Kimball"),
            ("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
            ("To succeed in life, you need two things: ignorance and confidence.", "Mark Twain"),
            ("The only way to achieve the impossible is to believe it is possible.", "Charles Kingsleigh"),
            ("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"),
            ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
            ("If you tell the truth, you don't have to remember anything.", "Mark Twain"),
            ("The man who moves a mountain begins by carrying away small stones.", "Confucius"),
            ("Do what you can, with what you have, where you are.", "Arthur Ashe"),
            ("Believe in yourself and all that you are.", "Christian D. Larson"),
            ("It is never too late to be what you might have been.", "George Eliot"),
            ("Life isn’t about finding yourself. Life is about creating yourself.", "George Bernard Shaw"),
            ("Happiness depends upon ourselves.", "Aristotle"),
            ("Don’t let yesterday take up too much of today.", "Will Rogers"),
            ("Don’t gain the world and lose your soul.", "Bob Marley"),
            ("Strive not to be a success, but rather to be of value.", "Albert Einstein"),
            ("Change your thoughts and you change your world.", "Norman Vincent Peale"),
            ("Do one thing every day that scares you.", "Mary Schmich"),
            ("If opportunity doesn't knock, build a door.", "Milton Berle"),
            ("The best dreams happen when you're awake.", "Cherie Gilderbloom"),
            ("Life is either a daring adventure or nothing at all.", "Helen Keller"),
            ("What you do makes a difference, and you have to decide what kind of difference you want to make.", "Jane Goodall"),
            ("Don’t compromise yourself – you’re all you have.", "Janis Joplin"),
            ("One child, one teacher, one book, and one pen can change the world.", "Malala Yousafzai"),
            ("Keep your face always toward the sunshine—and shadows will fall behind you.", "Walt Whitman"),
            ("Knowing yourself is the beginning of all wisdom.", "Aristotle"),
            ("Happiness is not by chance, but by choice.", "Jim Rohn"),
            ("Life is short, and it's up to you to make it sweet.", "Sarah Louise Delany"),
            ("The power of imagination makes us infinite.", "John Muir"),
            ("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
            ("You only live once, but if you do it right, once is enough.", "Mae West"),
            ("Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", "Roy T. Bennett"),
            ("Courage is grace under pressure.", "Ernest Hemingway"),
            ("Life becomes easier when you learn to accept the apology you never got.", "Robert Brault"),
            ("Don’t cry because it’s over, smile because it happened.", "Dr. Seuss"),
            ("Happiness is not something you postpone for the future; it is something you design for the present.", "Jim Rohn"),
            ("Light tomorrow with today.", "Elizabeth Barrett Browning"),
            ("The meaning of life is to find your gift. The purpose of life is to give it away.", "Pablo Picasso"),
            ("Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"),
            ("I would rather die of passion than of boredom.", "Vincent Van Gogh"),
            ("Don’t let the noise of others’ opinions drown out your own inner voice.", "Roy T. Bennett"),
            ("Normality is a paved road: it’s comfortable to walk, but no flowers grow on it.", "Vincent Van Gogh"),
            ("You were born to be a player. You were meant to be here. This moment is yours.", "Herb Brooks"),
            ("Do what you feel in your heart to be right – for you’ll be criticized anyway.", "Eleanor Roosevelt"),
            ("Love the life you live. Live the life you love.", "Bob Marley"),
            ("Be not afraid of going slowly, be afraid only of standing still.", "Chinese Proverb"),
            ("The more I want to get something done, the less I call it work.", "Richard Bach"),
            ("Doubt kills more dreams than failure ever will.", "Suzy Kassem"),
            ("Failure is simply the opportunity to begin again, this time more intelligently.", "Henry Ford"),
            ("Always do your best. What you plant now, you will harvest later.", "Og Mandino"),
            ("Do not wait for the perfect time and place to enter, for you are already onstage.", "Unknown"),
            ("Sometimes you win, sometimes you learn.", "John C. Maxwell"),
            ("There is no greater agony than bearing an untold story inside you.", "Maya Angelou"),
            ("Don’t quit. Suffer now and live the rest of your life as a champion.", "Muhammad Ali"),
            ("Inspiration exists, but it has to find you working.", "Pablo Picasso"),
            ("Your present circumstances don’t determine where you can go; they merely determine where you start.", "Nido Qubein"),
            ("Leap and the net will appear.", "John Burroughs"),
            ("Live out of your imagination, not your history.", "Stephen R. Covey"),
            ("It is our choices that show what we truly are, far more than our abilities.", "J.K. Rowling"),
            ("Stay close to anything that makes you glad you are alive.", "Hafez"),
            ("Action is the foundational key to all success.", "Pablo Picasso"),
            ("A winner is a dreamer who never gives up.", "Nelson Mandela"),
            ("Perseverance is not a long race; it is many short races one after the other.", "Walter Elliot"),
            ("I am not a product of my circumstances. I am a product of my decisions.", "Stephen R. Covey"),
            ("Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.", "Earl Nightingale"),
            ("Motivation is what gets you started. Habit is what keeps you going.", "Jim Ryun"),
            ("Push yourself, because no one else is going to do it for you.", "Unknown"),
            ("A goal without a plan is just a wish.", "Antoine de Saint-Exupéry"),
            ("Don’t limit your challenges. Challenge your limits.", "Jerry Dunn"),
            ("If you're going through hell, keep going.", "Eric Thomas"),
            ("You miss 100% of the shots you don’t take.", "Wayne Gretzky"),
            ("Don’t tell people your plans. Show them your results.", "Unknown"),
            ("Discipline is the bridge between goals and accomplishment.", "Jim Rohn"),
            ("Don’t be afraid to give up the good to go for the great.", "John D. Rockefeller"),
            ("Success is walking from failure to failure with no loss of enthusiasm.", "Abraham Lincoln"),
            ("A comfort zone is a beautiful place, but nothing ever grows there.", "Unknown"),
            ("You don’t have to be great to start, but you have to start to be great.", "Zig Ziglar"),
            ("Success doesn’t come to you. You go to it.", "Marva Collins"),
            ("Work hard in silence, let your success be your noise.", "Frank Ocean"),
            ("One day or day one. You decide.", "Unknown"),
            ("Don’t let what you cannot do interfere with what you can do.", "John Wooden"),
            ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant"),
            ("The journey of a thousand miles begins with one step.", "Lao Tzu"),
            ("He who is not courageous enough to take risks will accomplish nothing in life.", "Muhammad Ali"),
            ("Success is not in what you have, but who you are.", "Bo Bennett"),
            ("Fear is only as deep as the mind allows.", "Japanese Proverb"),
            ("Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.", "Unknown"),
            ("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"),
            ("It’s not whether you get knocked down, it’s whether you get up.", "Vince Lombardi"),
            ("Even if you’re on the right track, you’ll get run over if you just sit there.", "Will Rogers"),
            ("Success is the sum of small efforts, repeated day-in and day-out.", "Robert Collier"),
            ("Only I can change my life. No one can do it for me.", "Carol Burnett"),
            ("Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, ‘I will try again tomorrow.’", "Mary Anne Radmacher"),
            ("It takes courage to grow up and become who you really are.", "E.E. Cummings"),
            ("Energy and persistence conquer all things.", "Benjamin Franklin"),
            ("The harder the conflict, the more glorious the triumph.", "Thomas Paine"),
            ("Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.", "Francis of Assisi"),
            ("Failure will never overtake me if my determination to succeed is strong enough.", "Og Mandino"),
            ("It always seems impossible until it’s done.", "Nelson Mandela"),
            ("You cannot swim for new horizons until you have courage to lose sight of the shore.", "William Faulkner"),
            ("Success is getting what you want, happiness is wanting what you get.", "Ingrid Bergman"),
            ("You must expect great things of yourself before you can do them.", "Michael Jordan"),
            ("The best revenge is massive success.", "Frank Sinatra"),
            ("You are confined only by the walls you build yourself.", "Andrew Murphy"),
            ("To live a creative life, we must lose our fear of being wrong.", "Joseph Chilton Pearce"),
            ("Great minds discuss ideas; average minds discuss events; small minds discuss people.", "Henry Thomas Buckle"),
            ("Go the extra mile. It’s never crowded there.", "Dr. Wayne Dyer"),
            ("Believe you can and you’re halfway there.", "Theodore Roosevelt"),
            ("If you don’t like the road you’re walking, start paving another one.", "Dolly Parton"),
            ("Don’t be satisfied with stories, how things have gone with others. Unfold your own myth.", "Rumi"),
            ("Failure is not the opposite of success; it’s part of success.", "Arianna Huffington"),
            ("Act as if what you do makes a difference. It does.", "William James"),
            ("The secret of getting ahead is getting started.", "Mark Twain"),
            ("A creative man is motivated by the desire to achieve, not by the desire to beat others.", "Ayn Rand"),
            ("In any moment of decision, the best thing you can do is the right thing.", "Unknown"),
            ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
            ("Make each day your masterpiece.", "John Wooden"),
            ("Aim for the moon. If you miss, you may hit a star.", "W. Clement Stone"),
            ("A year from now you may wish you had started today.", "Karen Lamb"),
            ("Do not fear failure but rather fear not trying.", "Roy T. Bennett"),
            ("We may encounter many defeats but we must not be defeated.", "Maya Angelou"),
            ("The question isn’t who is going to let me; it’s who is going to stop me.", "Ayn Rand"),
            ("A surplus of effort could overcome a deficit of confidence.", "Sonia Sotomayor"),
            ("Don’t downgrade your dream just to fit your reality. Upgrade your conviction to match your destiny.", "Stuart Scott"),
            ("We become what we think about most of the time.", "Earl Nightingale"),
            ("It’s not the load that breaks you down, it’s the way you carry it.", "Lou Holtz"),
            ("To be the best, you must be able to handle the worst.", "Wilson Kanadi"),
        ])

    conn.commit()
    conn.close()

if __name__ == '__main__':
    init_db()
    print("Database and tables created, sample quotes inserted.")